<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>API</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">API</h1>
<p class='attribute'><strong>测试人员 : </strong> Mongo</p>
<p class='attribute'><strong>开始时间 : </strong> 2020-02-07 12:53:46</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:00:02.305508</p>
<p class='attribute'><strong>测试结果 : </strong> 共 18，通过 12，失败 3，错误 3，通过率= 66.67%</p>

<p class='description'>API测试报告</p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 66.67% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 3 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 12 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 18 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='failClass warning'>
    <td>test_invest.InvestTest</td>
    <td class="text-center">7</td>
    <td class="text-center">5</td>
    <td class="text-center">2</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',7)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='pt1_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_1_管理员正常登录: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_1'>通过</button>
    <div id='div_pt1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt1_1'>通过</button>
    <div id='div_pt1_1' class="collapse in" align="left">
    <pre>
    
pt1_1: --- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\handlers.py", line 185, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:/Users/40219/PycharmProjects/request_test/run_test.py", line 20, in &lt;module&gt;
    runner.run(discover)  # 执行查找到的用例
  File "C:\Users\40219\PycharmProjects\request_test\libext\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Users\40219\PycharmProjects\request_test\libext\ddtnew.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 39, in test_login
    logger.info("测试method,测试url,data:",login_case.method, login_case.url, str_data)
Message: '测试method,测试url,data:'
Arguments: ('get', '/member/login', '{"mobilephone":"15810447656","pwd":"123456"}')
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:/Users/40219/PycharmProjects/request_test/run_test.py", line 20, in &lt;module&gt;
    runner.run(discover)  # 执行查找到的用例
  File "C:\Users\40219\PycharmProjects\request_test\libext\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Users\40219\PycharmProjects\request_test\libext\ddtnew.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 39, in test_login
    logger.info("测试method,测试url,data:",login_case.method, login_case.url, str_data)
Message: '测试method,测试url,data:'
Arguments: ('get', '/member/login', '{"mobilephone":"15810447656","pwd":"123456"}')
GET http://test.lemonban.com/futureloan/mvc/api/member/login


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_2_管理员加标: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_2'>通过</button>
    <div id='div_pt1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt1_2'>通过</button>
    <div id='div_pt1_2' class="collapse in" align="left">
    <pre>
    
pt1_2: --- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\handlers.py", line 185, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:/Users/40219/PycharmProjects/request_test/run_test.py", line 20, in &lt;module&gt;
    runner.run(discover)  # 执行查找到的用例
  File "C:\Users\40219\PycharmProjects\request_test\libext\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Users\40219\PycharmProjects\request_test\libext\ddtnew.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 39, in test_login
    logger.info("测试method,测试url,data:",login_case.method, login_case.url, str_data)
Message: '测试method,测试url,data:'
Arguments: ('get', '/loan/add', '{"memberId":"290670","title":"试试人品行不行，借个2W玩玩","amount":20000,"loanRate":"12.0","loanTerm":3,"loanDateType":0,"repaymemtWay":11,"biddingDays":5}')
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:/Users/40219/PycharmProjects/request_test/run_test.py", line 20, in &lt;module&gt;
    runner.run(discover)  # 执行查找到的用例
  File "C:\Users\40219\PycharmProjects\request_test\libext\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Users\40219\PycharmProjects\request_test\libext\ddtnew.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 39, in test_login
    logger.info("测试method,测试url,data:",login_case.method, login_case.url, str_data)
Message: '测试method,测试url,data:'
Arguments: ('get', '/loan/add', '{"memberId":"290670","title":"试试人品行不行，借个2W玩玩","amount":20000,"loanRate":"12.0","loanTerm":3,"loanDateType":0,"repaymemtWay":11,"biddingDays":5}')
GET http://test.lemonban.com/futureloan/mvc/api/loan/add
290670
sql是..... (123462,)


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_3' class='none'>
    <td class='failCase'><div class='testcase'>test_login_3_管理员审核: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_3'>失败</button>
    <div id='div_ft1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_3'>失败</button>
    <div id='div_ft1_3' class="collapse in" align="left">
    <pre>
    
ft1_3: --- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\handlers.py", line 185, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:/Users/40219/PycharmProjects/request_test/run_test.py", line 20, in &lt;module&gt;
    runner.run(discover)  # 执行查找到的用例
  File "C:\Users\40219\PycharmProjects\request_test\libext\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Users\40219\PycharmProjects\request_test\libext\ddtnew.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 39, in test_login
    logger.info("测试method,测试url,data:",login_case.method, login_case.url, str_data)
Message: '测试method,测试url,data:'
Arguments: ('post', '/loan/audit', '{"id":"123462","status":4}')
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:/Users/40219/PycharmProjects/request_test/run_test.py", line 20, in &lt;module&gt;
    runner.run(discover)  # 执行查找到的用例
  File "C:\Users\40219\PycharmProjects\request_test\libext\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Users\40219\PycharmProjects\request_test\libext\ddtnew.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 39, in test_login
    logger.info("测试method,测试url,data:",login_case.method, login_case.url, str_data)
Message: '测试method,测试url,data:'
Arguments: ('post', '/loan/audit', '{"id":"123462","status":4}')
POST http://test.lemonban.com/futureloan/mvc/api/loan/audit
Traceback (most recent call last):
  File "C:\Users\40219\PycharmProjects\request_test\libext\ddtnew.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 56, in test_login
    raise e
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 42, in test_login
    self.assertEqual(res.json()["code"], login_case.expected, "invest error")  # 执行不通过就login error
AssertionError: '20207' != '10001'
- 20207
+ 10001
 : invest error


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_4' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_4_投资人正常登录: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_4'>通过</button>
    <div id='div_pt1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt1_4'>通过</button>
    <div id='div_pt1_4' class="collapse in" align="left">
    <pre>
    
pt1_4: --- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\handlers.py", line 185, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:/Users/40219/PycharmProjects/request_test/run_test.py", line 20, in &lt;module&gt;
    runner.run(discover)  # 执行查找到的用例
  File "C:\Users\40219\PycharmProjects\request_test\libext\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Users\40219\PycharmProjects\request_test\libext\ddtnew.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 39, in test_login
    logger.info("测试method,测试url,data:",login_case.method, login_case.url, str_data)
Message: '测试method,测试url,data:'
Arguments: ('get', '/member/login', '{"mobilephone":"15810447656","pwd":"123456"}')
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:/Users/40219/PycharmProjects/request_test/run_test.py", line 20, in &lt;module&gt;
    runner.run(discover)  # 执行查找到的用例
  File "C:\Users\40219\PycharmProjects\request_test\libext\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Users\40219\PycharmProjects\request_test\libext\ddtnew.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 39, in test_login
    logger.info("测试method,测试url,data:",login_case.method, login_case.url, str_data)
Message: '测试method,测试url,data:'
Arguments: ('get', '/member/login', '{"mobilephone":"15810447656","pwd":"123456"}')
GET http://test.lemonban.com/futureloan/mvc/api/member/login


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_5' class='none'>
    <td class='failCase'><div class='testcase'>test_login_5_投资人正常投资: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_5'>失败</button>
    <div id='div_ft1_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_5'>失败</button>
    <div id='div_ft1_5' class="collapse in" align="left">
    <pre>
    
ft1_5: --- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\handlers.py", line 185, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:/Users/40219/PycharmProjects/request_test/run_test.py", line 20, in &lt;module&gt;
    runner.run(discover)  # 执行查找到的用例
  File "C:\Users\40219\PycharmProjects\request_test\libext\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Users\40219\PycharmProjects\request_test\libext\ddtnew.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 39, in test_login
    logger.info("测试method,测试url,data:",login_case.method, login_case.url, str_data)
Message: '测试method,测试url,data:'
Arguments: ('post', '/member/bidLoan', '{"memberId":"1112171","password":"123456","loanId":"123462","amount":"100"}')
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:/Users/40219/PycharmProjects/request_test/run_test.py", line 20, in &lt;module&gt;
    runner.run(discover)  # 执行查找到的用例
  File "C:\Users\40219\PycharmProjects\request_test\libext\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Users\40219\PycharmProjects\request_test\libext\ddtnew.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 39, in test_login
    logger.info("测试method,测试url,data:",login_case.method, login_case.url, str_data)
Message: '测试method,测试url,data:'
Arguments: ('post', '/member/bidLoan', '{"memberId":"1112171","password":"123456","loanId":"123462","amount":"100"}')
POST http://test.lemonban.com/futureloan/mvc/api/member/bidLoan
Traceback (most recent call last):
  File "C:\Users\40219\PycharmProjects\request_test\libext\ddtnew.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 56, in test_login
    raise e
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 42, in test_login
    self.assertEqual(res.json()["code"], login_case.expected, "invest error")  # 执行不通过就login error
AssertionError: '11008' != '10001'
- 11008
+ 10001
 : invest error


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_6' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_6_投资人投资不输入金额: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_6'>通过</button>
    <div id='div_pt1_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt1_6'>通过</button>
    <div id='div_pt1_6' class="collapse in" align="left">
    <pre>
    
pt1_6: --- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\handlers.py", line 185, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:/Users/40219/PycharmProjects/request_test/run_test.py", line 20, in &lt;module&gt;
    runner.run(discover)  # 执行查找到的用例
  File "C:\Users\40219\PycharmProjects\request_test\libext\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Users\40219\PycharmProjects\request_test\libext\ddtnew.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 39, in test_login
    logger.info("测试method,测试url,data:",login_case.method, login_case.url, str_data)
Message: '测试method,测试url,data:'
Arguments: ('post', '/member/bidLoan', '{"memberId":"1112171","password":"123456","loanId":"123462","amount":""}')
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:/Users/40219/PycharmProjects/request_test/run_test.py", line 20, in &lt;module&gt;
    runner.run(discover)  # 执行查找到的用例
  File "C:\Users\40219\PycharmProjects\request_test\libext\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Users\40219\PycharmProjects\request_test\libext\ddtnew.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 39, in test_login
    logger.info("测试method,测试url,data:",login_case.method, login_case.url, str_data)
Message: '测试method,测试url,data:'
Arguments: ('post', '/member/bidLoan', '{"memberId":"1112171","password":"123456","loanId":"123462","amount":""}')
POST http://test.lemonban.com/futureloan/mvc/api/member/bidLoan


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_7' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_7_投资人投资输入负数: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_7'>通过</button>
    <div id='div_pt1_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt1_7'>通过</button>
    <div id='div_pt1_7' class="collapse in" align="left">
    <pre>
    
pt1_7: --- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\handlers.py", line 185, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:/Users/40219/PycharmProjects/request_test/run_test.py", line 20, in &lt;module&gt;
    runner.run(discover)  # 执行查找到的用例
  File "C:\Users\40219\PycharmProjects\request_test\libext\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Users\40219\PycharmProjects\request_test\libext\ddtnew.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 39, in test_login
    logger.info("测试method,测试url,data:",login_case.method, login_case.url, str_data)
Message: '测试method,测试url,data:'
Arguments: ('post', '/member/bidLoan', '{"memberId":"1112171","password":"123456","loanId":"123462","amount":"-100"}')
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:/Users/40219/PycharmProjects/request_test/run_test.py", line 20, in &lt;module&gt;
    runner.run(discover)  # 执行查找到的用例
  File "C:\Users\40219\PycharmProjects\request_test\libext\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Users\40219\PycharmProjects\request_test\libext\ddtnew.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_invest.py", line 39, in test_login
    logger.info("测试method,测试url,data:",login_case.method, login_case.url, str_data)
Message: '测试method,测试url,data:'
Arguments: ('post', '/member/bidLoan', '{"memberId":"1112171","password":"123456","loanId":"123462","amount":"-100"}')
POST http://test.lemonban.com/futureloan/mvc/api/member/bidLoan


    </pre>
    </div>
    </td>
</tr>

<tr class='passClass warning'>
    <td>test_login.LoginTest</td>
    <td class="text-center">4</td>
    <td class="text-center">4</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c2',4)" class="detail" id='c2'>详细</a></td>
</tr>

<tr id='pt2_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_1: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt2_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt2_1'>通过</button>
    <div id='div_pt2_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt2_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt2_1'>通过</button>
    <div id='div_pt2_1' class="collapse in" align="left">
    <pre>
    
pt2_1: 第1条测试用例
get /member/login {"mobilephone":"15810447656","pwd":"123456"}
GET http://test.lemonban.com/futureloan/mvc/api/member/login
第1条测试用例:通过


    </pre>
    </div>
    </td>
</tr>

<tr id='pt2_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_2: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt2_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt2_2'>通过</button>
    <div id='div_pt2_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt2_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt2_2'>通过</button>
    <div id='div_pt2_2' class="collapse in" align="left">
    <pre>
    
pt2_2: 第2条测试用例
post /member/login {"mobilephone":"15800447656","pwd":"12345678"}
POST http://test.lemonban.com/futureloan/mvc/api/member/login
第2条测试用例:通过


    </pre>
    </div>
    </td>
</tr>

<tr id='pt2_3' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_3: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt2_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt2_3'>通过</button>
    <div id='div_pt2_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt2_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt2_3'>通过</button>
    <div id='div_pt2_3' class="collapse in" align="left">
    <pre>
    
pt2_3: 第3条测试用例
get /member/login {"mobilephone":"15800447656","pwd":""}
GET http://test.lemonban.com/futureloan/mvc/api/member/login
第3条测试用例:通过


    </pre>
    </div>
    </td>
</tr>

<tr id='pt2_4' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_4: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt2_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt2_4'>通过</button>
    <div id='div_pt2_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt2_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt2_4'>通过</button>
    <div id='div_pt2_4' class="collapse in" align="left">
    <pre>
    
pt2_4: 第4条测试用例
post /member/login {"mobilephone":"","pwd":"123456"}
POST http://test.lemonban.com/futureloan/mvc/api/member/login
第4条测试用例:通过


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>test_register.RegisterTest</td>
    <td class="text-center">7</td>
    <td class="text-center">3</td>
    <td class="text-center">1</td>
    <td class="text-center">3</td>
    <td class="text-center"><a href="javascript:showClassDetail('c3',7)" class="detail" id='c3'>详细</a></td>
</tr>

<tr id='ft3_1' class='none'>
    <td class='failCase'><div class='testcase'>test_login_1: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_1'>失败</button>
    <div id='div_ft3_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_1'>失败</button>
    <div id='div_ft3_1' class="collapse in" align="left">
    <pre>
    
ft3_1: 第1条测试用例
get /member/register {'mobilephone': 63131441, 'pwd': '123456'}
GET http://test.lemonban.com/futureloan/mvc/api/member/register
第1条测试用例:失败
Traceback (most recent call last):
  File "C:\Users\40219\PycharmProjects\request_test\venv\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_register.py", line 45, in test_login
    raise e
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_register.py", line 39, in test_login
    self.assertEqual(res.text, login_case.expected, "reqister error")  # 执行不通过就login error
AssertionError: '{"status":0,"code":"20109","data":null,"msg":"手机号码格式不正确"}' != '{"status":1,"code":"10001","data":null,"msg":"注册成功"}'
- {"status":0,"code":"20109","data":null,"msg":"手机号码格式不正确"}
?           ^         ^  --                     ^^^^^^^^^
+ {"status":1,"code":"10001","data":null,"msg":"注册成功"}
?           ^         ^^^                       ^^^^
 : reqister error


    </pre>
    </div>
    </td>
</tr>

<tr id='pt3_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_2: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt3_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt3_2'>通过</button>
    <div id='div_pt3_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt3_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt3_2'>通过</button>
    <div id='div_pt3_2' class="collapse in" align="left">
    <pre>
    
pt3_2: 第2条测试用例
post /member/register {'mobilephone': '15800447656', 'pwd': ''}
POST http://test.lemonban.com/futureloan/mvc/api/member/register
第2条测试用例:通过


    </pre>
    </div>
    </td>
</tr>

<tr id='pt3_3' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_3: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt3_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt3_3'>通过</button>
    <div id='div_pt3_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt3_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt3_3'>通过</button>
    <div id='div_pt3_3' class="collapse in" align="left">
    <pre>
    
pt3_3: 第3条测试用例
get /member/register {'mobilephone': '', 'pwd': '12345678'}
GET http://test.lemonban.com/futureloan/mvc/api/member/register
第3条测试用例:通过


    </pre>
    </div>
    </td>
</tr>

<tr id='pt3_4' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_4: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt3_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt3_4'>通过</button>
    <div id='div_pt3_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt3_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt3_4'>通过</button>
    <div id='div_pt3_4' class="collapse in" align="left">
    <pre>
    
pt3_4: 第4条测试用例
post /member/register {'mobilephone': '13800000000', 'pwd': '12345678'}
POST http://test.lemonban.com/futureloan/mvc/api/member/register
第4条测试用例:通过


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_login_5: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_5'>错误</button>
    <div id='div_ft3_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_5'>错误</button>
    <div id='div_ft3_5' class="collapse in" align="left">
    <pre>
    
ft3_5: Traceback (most recent call last):
  File "C:\Users\40219\PycharmProjects\request_test\venv\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_register.py", line 32, in test_login
    data_dict = json.loads(login_case.data)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_login_6: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_6'>错误</button>
    <div id='div_ft3_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_6'>错误</button>
    <div id='div_ft3_6' class="collapse in" align="left">
    <pre>
    
ft3_6: Traceback (most recent call last):
  File "C:\Users\40219\PycharmProjects\request_test\venv\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_register.py", line 32, in test_login
    data_dict = json.loads(login_case.data)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_7' class='none'>
    <td class='errorCase'><div class='testcase'>test_login_7: 封装测试用例</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_7'>错误</button>
    <div id='div_ft3_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_7'>错误</button>
    <div id='div_ft3_7' class="collapse in" align="left">
    <pre>
    
ft3_7: Traceback (most recent call last):
  File "C:\Users\40219\PycharmProjects\request_test\venv\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\40219\PycharmProjects\request_test\testcases\test_register.py", line 32, in test_login
    data_dict = json.loads(login_case.data)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType


    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>18</td>
    <td>12</td>
    <td>3</td>
    <td>3</td>
    <td>通过率：66.67%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
